@baseUrl = http://127.0.0.1:3000/api/v1

### 1. Login to Get Access Token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "alice@example.com",
    "password": "StrongPassword123" 
}

### 2. Get All Users Using Access Token
GET {{baseUrl}}/users/
Authorization: Bearer {{login.response.body.access_token}}

### 2.1 Get All Users Using Access Token
GET {{baseUrl}}/users/1
Authorization: Bearer {{login.response.body.access_token}}


### 2.2. Create a New User (POST /api/v1/users/)
# This endpoint does not require authentication.
POST {{baseUrl}}/users/
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
    "email": "britney1211@example.com",
    "password": "StrongPassword123",
    "passwordConfirm": "StrongPassword123",
    "name": "Britney Spears",
    "stepLength": 0.75
}
### 2.3. Update an Existing User (PUT /api/v1/users/{user_id})
# This endpoint does not require authentication.
PUT {{baseUrl}}/users/1
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
    "email": "aliceup@example.com",
    "name": "AliceUp CuperUp",
    "stepLength": 0.95
}

### 2.4 Get All Users Using Access Token
GET {{baseUrl}}/users/user/dashboard/init
Authorization: Bearer {{login.response.body.access_token}}

### 2.5 Get All Users Using Access Token
DELETE {{baseUrl}}/users/1
Authorization: Bearer {{login.response.body.access_token}}

### 3. Get All Teams Using Access Token
GET {{baseUrl}}/teams/
Authorization: Bearer {{login.response.body.access_token}}

### 3.1 Create a New Team (POST /api/v1/teams/)
# This endpoint requires authentication using the obtained access token. 
POST {{baseUrl}}/teams/
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
    "name": "Team TEST"
}

### 3.2 Get All Teams Members from Team Challenge
GET {{baseUrl}}/teams/members/active_challenge/1/1
Authorization: Bearer {{login.response.body.access_token}}

### 3.3 Add user to team
POST {{baseUrl}}/teams/join_team/20
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
    "user_id": 15
}

### 3.4 Update a Team (PUT /api/v1/teams/1)
PUT {{baseUrl}}/teams/1
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
    "name": "Team TEST1"
}

### 4. Get All Team Members Using Access Token
GET {{baseUrl}}/team_members
Authorization: Bearer {{login.response.body.access_token}}

### 4.1 Get All Team Members Using Access Token
GET {{baseUrl}}/team_members/1
Authorization: Bearer {{login.response.body.access_token}}

### 4.2 Get All Team Members Using Access Token
GET {{baseUrl}}/team_members/team/1
Authorization: Bearer {{login.response.body.access_token}}

### 4.3 Create a New Team Member (POST /api/v1/teams/)
# This endpoint requires authentication using the obtained access token. 
POST {{baseUrl}}/team_members/
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
    "teamId": 2
}


### 5. Get All Challanges Using Access Token
GET {{baseUrl}}/challenges/
Authorization: Bearer {{login.response.body.access_token}}

### 5.1 Create a New Challenge (POST /api/v1/challenges/) 
POST {{baseUrl}}/challenges/
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
    "name": "Another Nice Challenge",
    "startLocation": "Liverpool", 
    "targetLocation": "London", 
    "distance": 300.0, 
    "startDate": "2025-05-01T00:00:00", 
    "endDate": "2025-06-01T00:00:00", 
    "teamId": 2,
    "creatorId": 1,
    "state": "incoming"  
}

### 5.2 Get All Challanges Using Access Token
GET {{baseUrl}}/challenges/1
Authorization: Bearer {{login.response.body.access_token}}

### 5.3 Delete a Challenge
DELETE {{baseUrl}}/challenges/1
Authorization: Bearer {{login.response.body.access_token}}

### 5.4 Update a Challenge (PUT /api/v1/challenges/20) 
PUT {{baseUrl}}/challenges/20
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
    "name": "Another Nice Challenge1",
    "startLocation": "Liverpool1", 
    "targetLocation": "London1", 
    "distance": 500.0, 
    "startDate": "2025-06-01T00:00:00", 
    "endDate": "2025-07-01T00:00:00", 
    "teamId": 2,
    "creatorId": 1,
    "state": "closed"  
}

### 6. Get All Challange_progresses Using Access Token
GET {{baseUrl}}/challenge_progress/
Authorization: Bearer {{login.response.body.access_token}}

### 7. Get All Step_logs Using Access Token
GET {{baseUrl}}/step_logs/
Authorization: Bearer {{login.response.body.access_token}}
### 8. Get All Step_logs Using Access Token
GET {{baseUrl}}/step_logs/user/1
Authorization: Bearer {{login.response.body.access_token}}

### 9. Create a New Step_log (POST /api/v1/step_logs/)
POST {{baseUrl}}/step_logs/
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "challengeId": 10,
  "teamId": 3,
  "date": "2025-08-06T08:00:00",
  "numberOfSteps": 12000
}

### 10. Admin Update a Step_log
PUT {{baseUrl}}/step_logs/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "numberOfSteps": 15000
}

### 11. User Update a Step_log
PUT {{baseUrl}}/step_logs?step_log_id=1
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "numberOfSteps": 20000
}