@baseUrl = http://127.0.0.1:3000/api/v1

### 1. Login to Get Access Token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "alice@example.com",
    "password": "StrongPassword123" 
}

### 2. Get All Users Using Access Token
GET {{baseUrl}}/users/
Authorization: Bearer {{login.response.body.access_token}}

### 3. Get All Teams Using Access Token
GET {{baseUrl}}/teams/
Authorization: Bearer {{login.response.body.access_token}}

### 4. Get All Team Members Using Access Token
GET {{baseUrl}}/team_members
Authorization: Bearer {{login.response.body.access_token}}


### 4.1 Get All Team Members Using Access Token
GET {{baseUrl}}/team_members/1
Authorization: Bearer {{login.response.body.access_token}}

### 4.2 Get All Team Members Using Access Token
GET {{baseUrl}}/team-members/team/1
Authorization: Bearer {{login.response.body.access_token}}


### 5. Get All Challanges Using Access Token
GET {{baseUrl}}/challenges/
Authorization: Bearer {{login.response.body.access_token}}

### 5.1 Get All Challanges Using Access Token
GET {{baseUrl}}/challenges/1
Authorization: Bearer {{login.response.body.access_token}}

### 6. Get All Challange_progresses Using Access Token
GET {{baseUrl}}/challenge_progress/
Authorization: Bearer {{login.response.body.access_token}}

### 7. Get All Step_logs Using Access Token
GET {{baseUrl}}/step_logs/
Authorization: Bearer {{login.response.body.access_token}}
### 8. Get All Step_logs Using Access Token
GET {{baseUrl}}/step_logs/user/1
Authorization: Bearer {{login.response.body.access_token}}